[package]
name = "cfx"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
byteorder = "1.5.0"
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }
clap = { version = "4.6.6", features = ["derive"] }
indicatif = "0.18.6"
rand = "0.10.2"
rpassword = "7.5.4"
thiserror = "2.0.20"

[dev-dependencies]
assert_cmd = "2.2.2"
predicates = "3.1.4"
tempfile = "3.27.0"
